# Generated by Django 5.2.17 on 2026-08-07 21:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_attribut', models.CharField(max_length=80, unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('portee', models.CharField(choices=[('ENVOI', 'Envoi'), ('SERVICE', 'Service')], max_length=15)),
                ('type_valeur', models.CharField(choices=[('TEXTE', 'Texte'), ('NOMBRE', 'Nombre'), ('DATE', 'Date'), ('BOOLEEN', 'Booléen')], max_length=15)),
                ('unite', models.CharField(blank=True, max_length=30)),
                ('sensible', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'attribut_definition',
            },
        ),
        migrations.CreateModel(
            name='FluxSynchronisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_flux', models.CharField(max_length=150)),
                ('sens_fonctionnel', models.CharField(max_length=255)),
                ('priorite', models.PositiveSmallIntegerField(default=1)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'flux_synchronisation',
            },
        ),
        migrations.CreateModel(
            name='GroupeResponsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_groupe', models.CharField(max_length=150)),
                ('email_collectif', models.EmailField(blank=True, max_length=254)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'groupe_responsable',
            },
        ),
        migrations.CreateModel(
            name='ModeleML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_modele', models.CharField(max_length=100)),
                ('algorithme', models.CharField(max_length=100)),
                ('version_modele', models.CharField(max_length=40, unique=True)),
                ('entraine_le', models.DateTimeField()),
                ('nb_exemples', models.PositiveIntegerField()),
                ('metriques', models.JSONField()),
                ('chemin_fichier', models.CharField(max_length=500)),
                ('checksum_sha256', models.CharField(max_length=64, unique=True)),
                ('actif', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'modele_ml',
            },
        ),
        migrations.CreateModel(
            name='Motif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_motif', models.CharField(max_length=80, unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('niveau_applicable', models.CharField(choices=[('ENVOI', 'Envoi'), ('SERVICE', 'Service'), ('ATTRIBUT', 'Attribut')], max_length=15)),
                ('categorie', models.CharField(max_length=20)),
                ('champ_typique', models.CharField(blank=True, max_length=80)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'motif',
            },
        ),
        migrations.CreateModel(
            name='ServiceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_service', models.CharField(max_length=50, unique=True)),
                ('libelle_reference', models.CharField(max_length=255)),
                ('categorie_service', models.CharField(db_index=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'service_reference',
            },
        ),
        migrations.CreateModel(
            name='Systeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_systeme', models.CharField(max_length=10, unique=True)),
                ('nom_systeme', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('ordre_comparaison', models.PositiveSmallIntegerField(unique=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'systeme',
                'ordering': ['ordre_comparaison'],
            },
        ),
        migrations.CreateModel(
            name='Superviseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nom_complet', models.CharField(blank=True, max_length=150)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'superviseur',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CampagneSupervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_declenchement', models.CharField(default='MANUEL', max_length=15)),
                ('org_commerciale', models.CharField(default='2000', max_length=10)),
                ('version_moteur', models.CharField(default='1.0.0', max_length=30)),
                ('statut', models.CharField(choices=[('PREPAREE', 'Préparée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ECHEC', 'Échec')], default='PREPAREE', max_length=20)),
                ('demarree_le', models.DateTimeField(auto_now_add=True)),
                ('terminee_le', models.DateTimeField(blank=True, null=True)),
                ('nb_anomalies', models.PositiveIntegerField(default=0)),
                ('message_erreur', models.TextField(blank=True)),
                ('superviseur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campagne_supervision',
            },
        ),
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('ENVOI', 'Envoi'), ('SERVICE', 'Service'), ('ATTRIBUT', 'Attribut')], max_length=15)),
                ('type_ecart', models.CharField(choices=[('ABSENT', 'Absent'), ('DIFFERENT', 'Différent')], max_length=20)),
                ('code_envoi', models.CharField(db_index=True, max_length=40)),
                ('code_service', models.CharField(blank=True, db_index=True, max_length=50)),
                ('empreinte_anomalie', models.CharField(max_length=64)),
                ('statut', models.CharField(choices=[('DETECTEE', 'Détectée'), ('ANALYSEE', 'Analysée'), ('VALIDEE', 'Validée'), ('NOTIFIEE', 'Notifiée'), ('RESOLUE', 'Résolue'), ('PERSISTANTE', 'Persistante')], db_index=True, default='DETECTEE', max_length=20)),
                ('gravite', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('CRITIQUE', 'Critique')], default='MOYENNE', max_length=15)),
                ('detectee_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cloturee_le', models.DateTimeField(blank=True, null=True)),
                ('attribut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='supervision.attributdefinition')),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='supervision.campagnesupervision')),
                ('systeme_ecart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='supervision.systeme')),
            ],
            options={
                'db_table': 'anomalie',
            },
        ),
        migrations.CreateModel(
            name='FichierImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('chemin_stockage', models.CharField(max_length=500)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('statut_import', models.CharField(choices=[('RECU', 'Reçu'), ('VALIDE', 'Validé'), ('CHARGE', 'Chargé'), ('ECHEC', 'Échec')], default='RECU', max_length=20)),
                ('nb_lignes_source', models.PositiveIntegerField(default=0)),
                ('nb_lignes_retenues', models.PositiveIntegerField(default=0)),
                ('importe_le', models.DateTimeField(auto_now_add=True)),
                ('message_erreur', models.TextField(blank=True)),
                ('superviseur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('systeme', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supervision.systeme')),
            ],
            options={
                'db_table': 'fichier_import',
            },
        ),
        migrations.CreateModel(
            name='EnvoiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_envoi', models.CharField(db_index=True, max_length=40)),
                ('num_commande', models.CharField(blank=True, db_index=True, max_length=40)),
                ('org_commerciale', models.CharField(default='2000', max_length=10)),
                ('date_commande', models.DateField(blank=True, null=True)),
                ('ligne_premiere', models.PositiveIntegerField()),
                ('empreinte_envoi', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fichier_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envois', to='supervision.fichierimport')),
            ],
            options={
                'db_table': 'envoi_snapshot',
            },
        ),
        migrations.CreateModel(
            name='ContactGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('fonction', models.CharField(blank=True, max_length=120)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='supervision.grouperesponsable')),
            ],
            options={
                'db_table': 'contact_groupe',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueAnomalie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, max_length=20)),
                ('nouveau_statut', models.CharField(max_length=20)),
                ('source_evenement', models.CharField(max_length=20)),
                ('commentaire', models.CharField(blank=True, max_length=500)),
                ('change_le', models.DateTimeField(auto_now_add=True)),
                ('anomalie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='supervision.anomalie')),
                ('superviseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historique_anomalie',
                'ordering': ['change_le'],
            },
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=40)),
                ('entite', models.CharField(db_index=True, max_length=80)),
                ('id_entite', models.PositiveBigIntegerField(db_index=True)),
                ('anciennes_valeurs', models.JSONField(blank=True, null=True)),
                ('nouvelles_valeurs', models.JSONField(blank=True, null=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('superviseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journal_audit',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('A_ENVOYER', 'À envoyer'), ('ENVOYEE', 'Envoyée'), ('ECHEC', 'Échec')], default='A_ENVOYER', max_length=20)),
                ('nb_tentatives', models.PositiveSmallIntegerField(default=0)),
                ('creee_le', models.DateTimeField(auto_now_add=True)),
                ('envoyee_le', models.DateTimeField(blank=True, null=True)),
                ('erreur', models.TextField(blank=True)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supervision.grouperesponsable')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='NotificationDestinataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_snapshot', models.CharField(max_length=150)),
                ('email_snapshot', models.EmailField(max_length=254)),
                ('statut_livraison', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ENVOYE', 'Envoyé'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=20)),
                ('envoyee_le', models.DateTimeField(blank=True, null=True)),
                ('erreur', models.CharField(blank=True, max_length=500)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.contactgroupe')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinataires', to='supervision.notification')),
            ],
            options={
                'db_table': 'notification_destinataire',
            },
        ),
        migrations.CreateModel(
            name='RegleMetier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_regle', models.CharField(max_length=80, unique=True)),
                ('niveau_anomalie', models.CharField(choices=[('ENVOI', 'Envoi'), ('SERVICE', 'Service'), ('ATTRIBUT', 'Attribut')], max_length=15)),
                ('type_controle', models.CharField(max_length=30)),
                ('expression_regle', models.JSONField()),
                ('seuil_confiance', models.DecimalField(decimal_places=4, default=1, max_digits=5)),
                ('priorite', models.PositiveSmallIntegerField(default=100)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attribut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='supervision.attributdefinition')),
                ('flux', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='supervision.fluxsynchronisation')),
                ('motif_suggere', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supervision.motif')),
            ],
            options={
                'db_table': 'regle_metier',
                'ordering': ['priorite'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_service', models.CharField(db_index=True, max_length=50)),
                ('libelle_service', models.CharField(blank=True, max_length=255)),
                ('numero_occurrence', models.PositiveSmallIntegerField(default=1)),
                ('ligne_source', models.PositiveIntegerField()),
                ('empreinte_service', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('envoi_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='supervision.envoisnapshot')),
                ('service_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='supervision.servicereference')),
            ],
            options={
                'db_table': 'service_snapshot',
            },
        ),
        migrations.CreateModel(
            name='ServiceAttributRegle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatoire', models.BooleanField(default=True)),
                ('regle_validation', models.JSONField(blank=True, null=True)),
                ('message_erreur', models.CharField(max_length=500)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attribut', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supervision.attributdefinition')),
                ('service_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='supervision.servicereference')),
                ('systeme', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supervision.systeme')),
            ],
            options={
                'db_table': 'service_attribut_regle',
            },
        ),
        migrations.CreateModel(
            name='RegleAffectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priorite', models.PositiveSmallIntegerField(default=1)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supervision.grouperesponsable')),
                ('motif', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supervision.motif')),
                ('systeme_a_corriger', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supervision.systeme')),
            ],
            options={
                'db_table': 'regle_affectation',
            },
        ),
        migrations.CreateModel(
            name='PredictionMotif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_prediction', models.CharField(choices=[('REGLE', 'Règle métier'), ('ML', 'Machine learning')], max_length=10)),
                ('rang', models.PositiveSmallIntegerField(default=1)),
                ('score_confiance', models.DecimalField(decimal_places=4, max_digits=5)),
                ('explication', models.JSONField(blank=True, null=True)),
                ('predite_le', models.DateTimeField(auto_now_add=True)),
                ('anomalie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='supervision.anomalie')),
                ('modele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='supervision.modeleml')),
                ('motif', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supervision.motif')),
                ('regle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='supervision.reglemetier')),
                ('systeme_a_corriger_predit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='supervision.systeme')),
            ],
            options={
                'db_table': 'prediction_motif',
            },
        ),
        migrations.AddField(
            model_name='grouperesponsable',
            name='systeme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supervision.systeme'),
        ),
        migrations.AddField(
            model_name='fluxsynchronisation',
            name='systeme_destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='flux_entrants', to='supervision.systeme'),
        ),
        migrations.AddField(
            model_name='fluxsynchronisation',
            name='systeme_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='flux_sortants', to='supervision.systeme'),
        ),
        migrations.CreateModel(
            name='DetailComparaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet_present', models.BooleanField()),
                ('valeur_brute', models.TextField(blank=True, null=True)),
                ('valeur_normalisee', models.CharField(blank=True, max_length=500, null=True)),
                ('format_source_conforme', models.BooleanField(blank=True, null=True)),
                ('est_ecart', models.BooleanField(default=False)),
                ('ligne_source', models.PositiveIntegerField(blank=True, null=True)),
                ('observation', models.CharField(blank=True, max_length=500)),
                ('anomalie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='supervision.anomalie')),
                ('systeme', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supervision.systeme')),
            ],
            options={
                'db_table': 'detail_comparaison',
            },
        ),
        migrations.CreateModel(
            name='CampagneImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_fichier', models.CharField(default='COMPARAISON', max_length=20)),
                ('associe_le', models.DateTimeField(auto_now_add=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='supervision.campagnesupervision')),
                ('fichier_import', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supervision.fichierimport')),
                ('systeme', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supervision.systeme')),
            ],
            options={
                'db_table': 'campagne_import',
            },
        ),
        migrations.CreateModel(
            name='ValeurAttributSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_brute', models.TextField(blank=True, null=True)),
                ('valeur_normalisee', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('valeur_numerique', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('valeur_date', models.DateField(blank=True, null=True)),
                ('est_vide', models.BooleanField(default=False)),
                ('format_source_conforme', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attribut', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supervision.attributdefinition')),
                ('envoi_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valeurs_attribut', to='supervision.envoisnapshot')),
                ('service_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valeurs_attribut', to='supervision.servicesnapshot')),
            ],
            options={
                'db_table': 'valeur_attribut_snapshot',
            },
        ),
        migrations.CreateModel(
            name='ValidationMotif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('ACCEPTE', 'Accepté'), ('MODIFIE', 'Modifié'), ('INCONNU', 'Inconnu')], max_length=15)),
                ('commentaire', models.TextField(blank=True)),
                ('version_validation', models.PositiveSmallIntegerField(default=1)),
                ('est_finale', models.BooleanField(default=True)),
                ('validee_le', models.DateTimeField(auto_now_add=True)),
                ('anomalie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='supervision.anomalie')),
                ('motif_final', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supervision.motif')),
                ('prediction_retenue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='supervision.predictionmotif')),
                ('superviseur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('systeme_a_corriger_final', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supervision.systeme')),
            ],
            options={
                'db_table': 'validation_motif',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='validation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notifications', to='supervision.validationmotif'),
        ),
        migrations.CreateModel(
            name='ExempleApprentissage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristiques', models.JSONField()),
                ('eligible', models.BooleanField(default=True)),
                ('raison_exclusion', models.CharField(blank=True, max_length=500)),
                ('version_dataset', models.CharField(blank=True, db_index=True, max_length=40)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('motif_label', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supervision.motif')),
                ('systeme_a_corriger_label', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supervision.systeme')),
                ('validation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supervision.validationmotif')),
            ],
            options={
                'db_table': 'exemple_apprentissage',
            },
        ),
        migrations.CreateModel(
            name='VerificationResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat', models.CharField(choices=[('RESOLUE', 'Résolue'), ('PERSISTANTE', 'Persistante'), ('INDETERMINABLE', 'Indéterminable')], max_length=20)),
                ('commentaire', models.CharField(blank=True, max_length=500)),
                ('verifiee_le', models.DateTimeField(auto_now_add=True)),
                ('anomalie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='supervision.anomalie')),
                ('campagne_controle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='supervision.campagnesupervision')),
            ],
            options={
                'db_table': 'verification_resolution',
            },
        ),
        migrations.AddConstraint(
            model_name='envoisnapshot',
            constraint=models.UniqueConstraint(fields=('fichier_import', 'code_envoi'), name='uq_import_code_envoi'),
        ),
        migrations.AddConstraint(
            model_name='contactgroupe',
            constraint=models.UniqueConstraint(fields=('groupe', 'email'), name='uq_contact_groupe_email'),
        ),
        migrations.AddConstraint(
            model_name='notificationdestinataire',
            constraint=models.UniqueConstraint(fields=('notification', 'email_snapshot'), name='uq_notification_email'),
        ),
        migrations.AddConstraint(
            model_name='servicesnapshot',
            constraint=models.UniqueConstraint(fields=('envoi_snapshot', 'code_service', 'numero_occurrence'), name='uq_envoi_service_occurrence'),
        ),
        migrations.AddConstraint(
            model_name='serviceattributregle',
            constraint=models.UniqueConstraint(fields=('service_ref', 'attribut', 'systeme'), name='uq_service_attr_systeme'),
        ),
        migrations.AddConstraint(
            model_name='regleaffectation',
            constraint=models.UniqueConstraint(fields=('systeme_a_corriger', 'motif'), name='uq_affectation_systeme_motif'),
        ),
        migrations.AddConstraint(
            model_name='predictionmotif',
            constraint=models.UniqueConstraint(fields=('anomalie', 'source_prediction', 'rang'), name='uq_anomalie_source_rang'),
        ),
        migrations.AddConstraint(
            model_name='grouperesponsable',
            constraint=models.UniqueConstraint(fields=('systeme', 'nom_groupe'), name='uq_groupe_systeme_nom'),
        ),
        migrations.AddConstraint(
            model_name='fluxsynchronisation',
            constraint=models.UniqueConstraint(fields=('systeme_source', 'systeme_destination'), name='uq_flux_source_destination'),
        ),
        migrations.AddConstraint(
            model_name='fluxsynchronisation',
            constraint=models.CheckConstraint(condition=models.Q(('systeme_source', models.F('systeme_destination')), _negated=True), name='ck_flux_systemes_distincts'),
        ),
        migrations.AddConstraint(
            model_name='fichierimport',
            constraint=models.UniqueConstraint(fields=('systeme', 'checksum_sha256'), name='uq_fichier_systeme_checksum'),
        ),
        migrations.AddConstraint(
            model_name='detailcomparaison',
            constraint=models.UniqueConstraint(fields=('anomalie', 'systeme'), name='uq_anomalie_systeme_detail'),
        ),
        migrations.AddConstraint(
            model_name='campagneimport',
            constraint=models.UniqueConstraint(fields=('campagne', 'systeme'), name='uq_campagne_systeme'),
        ),
        migrations.AddConstraint(
            model_name='campagneimport',
            constraint=models.UniqueConstraint(fields=('campagne', 'fichier_import'), name='uq_campagne_import'),
        ),
        migrations.AddConstraint(
            model_name='anomalie',
            constraint=models.UniqueConstraint(fields=('campagne', 'empreinte_anomalie'), name='uq_campagne_empreinte_anomalie'),
        ),
        migrations.AddConstraint(
            model_name='valeurattributsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('envoi_snapshot__isnull', False), ('service_snapshot__isnull', True)), models.Q(('envoi_snapshot__isnull', True), ('service_snapshot__isnull', False)), _connector='OR'), name='ck_valeur_parent_xor'),
        ),
        migrations.AddConstraint(
            model_name='valeurattributsnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('service_snapshot__isnull', True)), fields=('envoi_snapshot', 'attribut'), name='uq_envoi_attribut'),
        ),
        migrations.AddConstraint(
            model_name='valeurattributsnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('envoi_snapshot__isnull', True)), fields=('service_snapshot', 'attribut'), name='uq_service_attribut'),
        ),
        migrations.AddConstraint(
            model_name='validationmotif',
            constraint=models.UniqueConstraint(fields=('anomalie', 'version_validation'), name='uq_anomalie_version_validation'),
        ),
        migrations.AddConstraint(
            model_name='verificationresolution',
            constraint=models.UniqueConstraint(fields=('anomalie', 'campagne_controle'), name='uq_anomalie_campagne_controle'),
        ),
    ]
