# Generated by Django 5.2.17 on 2026-08-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0004_restore_attribute_value_differences'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='valeurattributsnapshot',
            name='uq_envoi_attribut',
        ),
        migrations.RemoveConstraint(
            model_name='valeurattributsnapshot',
            name='uq_service_attribut',
        ),
        migrations.AddConstraint(
            model_name='valeurattributsnapshot',
            constraint=models.UniqueConstraint(fields=('envoi_snapshot', 'attribut'), name='uq_envoi_attribut'),
        ),
        migrations.AddConstraint(
            model_name='valeurattributsnapshot',
            constraint=models.UniqueConstraint(fields=('service_snapshot', 'attribut'), name='uq_service_attribut'),
        ),
    ]
